---
- name: Install Apache2 and Depedency
  apt:
      name: "{{ item }}"
      state: present
      
  with_items:
      - apache2
      - libapache2-mod-php

- name: File Config WebServer 
  copy:
    src: moodle.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf

