---
- name: Install MySQL Server and dependency
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - mysql-client
      - mysql-server
      - python3-pip

- name: Install Module Pymysql
  become: true
  pip:
    name: pymysql
    state: present

- name: Set password for root user
  mysql_user:
    name: "root"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL,GRANT'
    host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Save root password in .my.cnf
  template:
    src: root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'
  
- name: Create Database Moodle
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present

- name: Create User DB
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: '*.*:ALL,GRANT'
    state: present