- name: Create Directory moodle if not exists
  ansible.builtin.file:
    path: /var/www/moodle
    state: directory
    mode: '0777'

- name: Git Repository
  git:
    repo: git://git.moodle.org/moodle.git
    dest: /var/www/moodle
    version: MOODLE_39_STABLE

- name: Create Directory if not exists
  ansible.builtin.file:
    path: /var/moodledata
    state: directory
    mode: '0777'

- name: Change Ownership
  ansible.builtin.file:
    path: /var/moodledata
    owner: www-data

